specVersion: 0.0.1
description: ""
repository: ""
schema: ./schema.graphql
network:
  # endpoint: wss://polkadot.api.onfinality.io/public-ws
  endpoint: wss://pub.elara.patract.io/polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7567149
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: handleBatchCall
          kind: substrate/CallHandler
